CREATE TABLE public.recommendation_scores (

    id uuid PRIMARY KEY DEFAULT gen_random_uuid(),

    profile_id uuid NOT NULL
        REFERENCES public.profiles(id)
        ON DELETE CASCADE,

    product_id uuid NOT NULL
        REFERENCES public.products(id)
        ON DELETE CASCADE,

    score numeric(6,2) NOT NULL DEFAULT 0,

    algorithm_version text NOT NULL DEFAULT 'v1',

    recommendation_reason text,

    metadata jsonb NOT NULL DEFAULT '{}'::jsonb,

    calculated_at timestamptz NOT NULL DEFAULT now(),

    expires_at timestamptz,

    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),

    CONSTRAINT recommendation_scores_unique
        UNIQUE (profile_id, product_id),

    CONSTRAINT recommendation_scores_score_check
        CHECK (
            score >= 0
            AND score <= 100
        )

);

CREATE INDEX idx_recommendation_scores_profile
ON public.recommendation_scores(profile_id);

CREATE INDEX idx_recommendation_scores_product
ON public.recommendation_scores(product_id);

CREATE INDEX idx_recommendation_scores_score
ON public.recommendation_scores(score DESC);

CREATE INDEX idx_recommendation_scores_calculated
ON public.recommendation_scores(calculated_at DESC);

ALTER TABLE public.recommendation_scores
ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users view own recommendation scores"
ON public.recommendation_scores
FOR SELECT
TO authenticated
USING (profile_id = auth.uid());

CREATE POLICY "System manage recommendation scores"
ON public.recommendation_scores
FOR ALL
TO service_role
USING (true)
WITH CHECK (true);

CREATE TRIGGER update_recommendation_scores_updated_at
BEFORE UPDATE
ON public.recommendation_scores
FOR EACH ROW
EXECUTE FUNCTION public.update_updated_at_column();

COMMENT ON TABLE public.recommendation_scores IS
'Stores recommendation scores generated by recommendation engines for each user and product.';